### ISSUE TITLE
Give back the maintainer right

### ISSUE THREAD

**Issue by bashu** [redsolution/django-seo#6]
Hi,

This repository seems to lack maintenance, I propose myself as a new maintainer.

Could you give me the right to push in your repository or just transfer it on my account in github?

Thank you

**Comment by a-iv** [comment]
@bashu You are welcome to create pull requests.

Thank you!

**Comment by bashu** [comment]
https://github.com/bashu/django-easy-seo nevermind

**Comment by summerisgone** [comment]
:-1:
